### ISSUE TITLE
[split_categorized] cannot generate configurations because of layer's name

### ISSUE THREAD

**Issue by acassand** [qwc-services/qwc-qgis-server-plugins#2]
**Observed behaviour** : 

- When I am trying to generate configuration after adding "convert_categorized_layer"=true variable to a layer which contains space character → qwc-config-service generate an error 

> CRITICAL in config_generator: ERROR generating thumbnail for WMS scan/proj_acd_demo
> <?xml version="1.0" encoding="UTF-8"?>\n<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">\n <ServiceException code="LayerNotDefined">The layer \'geographic_lines\' does not exist.</ServiceException>\n</ServiceExceptionReport>\n

**Expected behaviour** : 

- The layer's name "Geographic lines" shouldn't be a problem

**Attachments** : zip file contains two .qgs project  
- projet_demo_acd_OK.qgs : with layer's name "geographic_lines" and without convert_categorized_layer attribute
- projet_demo_acd_KO.qgs : with layer's name "Geographic lines" and with convert_categorized_layer attribute

[projet_demo_acd.zip](https://github.com/user-attachments/files/16379312/projet_demo_acd.zip)

**Comment by manisandro** [comment]
Works correctly for me. Perhaps related to [1]? See specifically [2].

[1] https://github.com/qgis/qwc2-demo-app/issues/524
[2] https://github.com/qgis/qwc2-demo-app/issues/524#issuecomment-2251026255

**Comment by acassand** [comment]
Wow! Problem solved. Thanks !
